# Q1

In [1]:
import numpy as np

In [40]:
# Define the matrix A
A = np.array([[0,4,3],[4,5,6],[7,8,9],[10,11,12]])
A

array([[ 0,  4,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
# Step 1: Compute A^T A and AA^T
AT = A.T
ATA = AT @ A
AAT = A @ AT

In [6]:
ATA

array([[165, 186, 207],
       [186, 226, 246],
       [207, 246, 270]])

In [7]:
AAT

array([[ 25,  38,  59,  80],
       [ 38,  77, 122, 167],
       [ 59, 122, 194, 266],
       [ 80, 167, 266, 365]])

In [8]:
# Step 2: Compute the eigenvalues and eigenvectors of A^T A and AA^T
eigvals_ATA, eigvecs_ATA = np.linalg.eig(ATA)
eigvals_AAT, eigvecs_AAT = np.linalg.eig(AAT)

In [9]:
eigvals_ATA

array([6.53506681e+02, 7.20667122e+00, 2.86648073e-01])

In [10]:
eigvecs_ATA

array([[-0.49498078, -0.82154238, -0.28295254],
       [-0.58503513,  0.55587585, -0.59053868],
       [-0.64243904,  0.12676812,  0.75577902]])

In [11]:
eigvals_AAT

array([6.53506681e+02, 7.20667122e+00, 2.86648073e-01, 1.38313037e-15])

In [12]:
eigvecs_AAT

array([[-1.66933771e-01, -9.69932603e-01,  1.77098451e-01,
         7.05704590e-15],
       [-3.42661928e-01, -9.45487378e-02, -8.40819049e-01,
         4.08248290e-01],
       [-5.44798135e-01,  6.06725238e-02, -1.81237883e-01,
        -8.16496581e-01],
       [-7.46934342e-01,  2.15893785e-01,  4.78343282e-01,
         4.08248290e-01]])

In [15]:
# Step 3: Sort the eigenvalues and corresponding eigenvectors
sorted_indices_ATA = np.argsort(eigvals_ATA)[::-1]
sorted_indices_AAT = np.argsort(eigvals_AAT)[::-1]

In [17]:
sorted_indices_ATA

array([0, 1, 2])

In [18]:
sorted_indices_AAT

array([0, 1, 2, 3])

In [19]:
# Sort eigenvectors according to the sorted eigenvalues
V = eigvecs_ATA[:,sorted_indices_ATA]
U = eigvecs_AAT[:,sorted_indices_AAT]

In [20]:
V

array([[-0.49498078, -0.82154238, -0.28295254],
       [-0.58503513,  0.55587585, -0.59053868],
       [-0.64243904,  0.12676812,  0.75577902]])

In [21]:
U

array([[-1.66933771e-01, -9.69932603e-01,  1.77098451e-01,
         7.05704590e-15],
       [-3.42661928e-01, -9.45487378e-02, -8.40819049e-01,
         4.08248290e-01],
       [-5.44798135e-01,  6.06725238e-02, -1.81237883e-01,
        -8.16496581e-01],
       [-7.46934342e-01,  2.15893785e-01,  4.78343282e-01,
         4.08248290e-01]])

In [25]:
# Step 4: Compute the singular values
sing_values = np.sqrt(eigvals_ATA[sorted_indices_ATA])
sing_values

array([25.56377673,  2.68452439,  0.53539525])

In [28]:
# Step 5: Construct the sigma matrix
Sigma = np.diag(sing_values)
Sigma

array([[25.56377673,  0.        ,  0.        ],
       [ 0.        ,  2.68452439,  0.        ],
       [ 0.        ,  0.        ,  0.53539525]])

In [30]:
# Adjust the dimensions of U, Sigma, and V to ensure they can be multiplied to give A.
Sigma = np.pad(Sigma, ((0, U.shape[0] - Sigma.shape[0]), (0, V.shape[1] - Sigma.shape[1])), 'constant')
Sigma

array([[25.56377673,  0.        ,  0.        ],
       [ 0.        ,  2.68452439,  0.        ],
       [ 0.        ,  0.        ,  0.53539525],
       [ 0.        ,  0.        ,  0.        ]])

In [31]:
# Print the results
print("U = \n", U)

U = 
 [[-1.66933771e-01 -9.69932603e-01  1.77098451e-01  7.05704590e-15]
 [-3.42661928e-01 -9.45487378e-02 -8.40819049e-01  4.08248290e-01]
 [-5.44798135e-01  6.06725238e-02 -1.81237883e-01 -8.16496581e-01]
 [-7.46934342e-01  2.15893785e-01  4.78343282e-01  4.08248290e-01]]


In [32]:
print("Sigma = \n", Sigma)

Sigma = 
 [[25.56377673  0.          0.        ]
 [ 0.          2.68452439  0.        ]
 [ 0.          0.          0.53539525]
 [ 0.          0.          0.        ]]


In [36]:
print("V^T = \n", V.T)
X = V.T

V^T = 
 [[-0.49498078 -0.58503513 -0.64243904]
 [-0.82154238  0.55587585  0.12676812]
 [-0.28295254 -0.59053868  0.75577902]]


In [42]:
A_reconstructed = A

In [41]:
# Step 6: Reconstruct A using the SVD
A_reconstructed = U @ Sigma @ X

In [43]:
A_reconstructed

array([[ 0,  4,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

When we multiply U, Sigma and V^T together, the resulting matrix is the original matrix A. This verifies that the SVD wa sperformed correctly, as the product of U, Sigma and V^T results in the expected original matrix A

# Q2